package com.redes_sociales.vistas;

import com.redes_sociales.controladores.ControladorGrafo;

import javax.swing.*;
import java.awt.*;

/**
 * Esta clase representa la vista de las islas en la aplicación de redes sociales.
 * Muestra el número de islas en el grafo de la red social.
 */
public class VistaIsla extends javax.swing.JFrame {
    
    
    
      private ControladorGrafo controladorGrafo;
    private JTextArea textArea;
    
    
        /**
     * Crea una nueva vista de isla con un controlador de grafo específico.
     *
     * @param controladorGrafo el controlador de grafo que se utilizará para obtener los datos del grafo.
     */


    public VistaIsla(ControladorGrafo controladorGrafo) {
        this.controladorGrafo = controladorGrafo;

        // Configuración básica de la ventana
        this.setTitle("Vista Isla");
        this.setSize(400, 300);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Crear una textArea para mostrar la información del grafo
        textArea = new JTextArea();
        textArea.setEditable(false);

        // Agregar un JScrollPane para permitir el desplazamiento cuando hay muchos datos
        JScrollPane scrollPane = new JScrollPane(textArea);
        this.add(scrollPane, BorderLayout.CENTER);

        initComponents();
    }
    
    
        /**
     * Muestra el número de islas en el grafo de la red social en el área de texto de la vista.
     */

    public void mostrarIslas() {
        int numIslas = controladorGrafo.contarIslas();
        textArea.append("Número de islas en el grafo: " + numIslas + "\n");
    }

 
    
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
